INSERT OR IGNORE INTO `Unit` (`id`, `name`, `abbreviation`, `createdAt`, `updatedAt`) VALUES
  ('unit-teaspoon', 'teaspoon', 'tsp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-tablespoon', 'tablespoon', 'tbsp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-cup', 'cup', 'cup', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-fluid-ounce', 'fluid ounce', 'fl oz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-ounce', 'ounce', 'oz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-pound', 'pound', 'lb', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-gram', 'gram', 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-kilogram', 'kilogram', 'kg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-milliliter', 'milliliter', 'mL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-liter', 'liter', 'L', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-pinch', 'pinch', 'pinch', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-dash', 'dash', 'dash', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-clove', 'clove', 'clove', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-slice', 'slice', 'slice', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-piece', 'piece', 'piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-whole', 'whole', 'whole', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-stick', 'stick', 'stick', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-can', 'can', 'can', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('unit-package', 'package', 'pkg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
